### ISSUE TITLE
Godot 4.0 support

### ISSUE THREAD

**Issue by Inve1951** [thimenesup/GodotZigBindings#1]
Godot 4.0 (current master) will have a new API: [Introducing GDNative's successor, GDExtension](https://godotengine.org/article/introducing-gd-extensions)

**Comment by PDeveloper** [comment]
+1 for this - is this something in scope for this project that is planned?

I might try to adapt it to Godot 4.0 if it indeed is easy enough to translate, but it would be great to start incorporating Zig, especially for plugins because of ease of cross compilation.

**Comment by CashWasabi** [comment]
Hey, I was recently also very interested in using Godot with Zig. 
I am pretty new though to bindings and also to Godot.
Since the approach to bindings changed a bit I was curious about your approach and if it can be applicable to the new bindings.
Maybe if you have some tips or even some intentions to support 4.0+ at some point yourself?

**Comment by egsam98** [comment]
Seems like project is abandoned

**Comment by kassane** [comment]
> Godot 4.0 (current master) will have a new API: [Introducing GDNative's successor, GDExtension](https://godotengine.org/article/introducing-gd-extensions)

The interesting thing is that godot can generate a dump in C code.
https://gist.github.com/kassane/e8ff690996aa0be1172def45948130a2

**Comment by thimenesup** [comment]
Master branch now supports 4.0 GDExtension.
